## makeCacheMatrix can cache matrix x or the inverse of matrix x.  It 
## creates a special matrix, which is a list of four functions that can cache 
## the inverse of a matrix using the cacheSolve function.

makeCacheMatrix <- function(x = matrix(r, c)) {
	matinv <- NULL
        set <- function(y){
                x <<- y
                matinv <<- NULL
        }
        get <- function() x
        setinv <- function(inv) matinv <<- inv
        getinv <- function() matinv
        list(set = set, get = get,
             setinv = setinv,
             getinv = getinv)
}


## cacheSolve first determines whether the inverse of the special matrix 
## generated by makeCacheMatrix is stored in the cache and if so, will return
## the message "getting cached data" and the inverted matrix. Otherwise,
## it will cache the matrix and then display the inverse of the special 
## matrix from the cache 

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        ##x is the value of makeCacheMatrix
        inverted <- x$getinv()
        if(!is.null(inverted)) {
                message("getting cached data")
                return(inverted)
        }
        data <- x$get()
        inverse <- solve(data)
        x$setinv(inverse)
        inverse
}
